export const products = [
  {
    key: "Shirts",
    tittle: "Shirts",
    products: [
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "White/Black Stripe Classic Fit Shirt",
        discountedPrice: 6380.0,
        price: 7975.0,
        link: "/",
      },
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "Stripe White/Sky Tailored Smart Fit Shirt",
        discountedPrice: 7180.0,
        price: 8975.0,
        link: "/",
      },
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "Camel Self Tailored Smart Fit Shirt",
        discountedPrice: 4796.0,
        price: 5995.0,
        link: "/",
      },
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "Plain Navy Classic Fit Shirt",
        discountedPrice: 3571.0,
        price: 5495.0,
        link: "/",
      },
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "Plain L Grey Classic Fit Shirt",
        discountedPrice: 3996.0,
        price: 4895.0,
        link: "/",
      },
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "Sky Check Tailored Smart Fit Shirt",
        discountedPrice: 6380.0,
        price: 7975.0,
        link: "/",
      },
    ],
  },
  {
    key: "Accessories",
    tittle: "Accessories",
    products: [
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "Brown 100% Leather Wallet",
        discountedPrice: 3036.0,
        price: 3795.0,
        link: "/",
      },
    ],
  },
  {
    key: "Summer Collection",
    tittle: "Summer Collection",
    products: [
      {
        images: [
          "https://uniworthdress.com/uploads/product/FS1065RF..jpg",
          "https://uniworthdress.com/uploads/product/FS1065RF...jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF.....jpg",
          "https://uniworthdress.com/uploads/product/FS1081-3SF....jpg",
        ],
        desc: "T Green Plain Pique Polo Shirt",
        discountedPrice: 2796.0,
        price: 3495.0,
        link: "/",
      },
    ],
  },
];
export const data = [
  // Summer Collection 
  // T-Shirts
  {
    id:7,
    name:"1947 Grey Crew Neck T-shirt",
    brand:"Graphic Tees",
    category:"Summer Collection",
    subCategory:"T Shirts",
    totalPrice:2295,
    discountedPrice:1836,
    productedDetail:[
      {Color:"Grey"},
      {Sleeve:"Half Sleeves"},
      {Fit:"Crew Fit"},
      {CuffStyle:"Hem"},
      {CollarStyle:"Crew Neck"},
      {Pattern:"Plain"},
      {Style:"Printed"},
      {Fabric:"100% Cotton"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 0 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 10 },
    ],
    desc:"This special shirt is designed to celebrate history and independence in style. Crafted from premium cotton, this crew neck t-shirt offers ultimate comfort and durability. The bold and distinctive 1947 graphic print pays homage to the year of Pakistan’s independence, making it a perfect blend of fashion and heritage. Its light grey color is versatile and easy to match with any trousers or pants.",
    images:["https://uniworthdress.com/uploads/product/b12b0d66a7f573853b914380e94981f1.jpg","https://uniworthdress.com/uploads/product/d638175faf8e97bd47a1806a9ff6d116.jpg","https://uniworthdress.com/uploads/product/TCN2445.jpg","https://uniworthdress.com/uploads/product/TCN2445...jpg"]
  },
  {
    id:8,
    name:"Navy Stripe Band Collar Cotton T-shirt",
    category:"Summer Collection",
    subCategory:"T Shirts",
    brand:"Sale",
    totalPrice:3595,
    discountedPrice:2337,
    productedDetail:[
      {Color:"Navy"},
      {Sleeve:"Half Sleeves"},
      {Fit:"Regular Fit"},
      {CuffStyle:"Rib"},
      {CollarStyle:"Band Collar"},
      {Pattern:"Stripe"},
      {Style:"Yarn Dyed"},
      {Fabric:"100% Cotton"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"This shirt features a sleek and minimalistic collar band, typically measuring two to five centimeters in height, running seamlessly around the neckline without any folding or turndown. It’s perfect for pairing with denim jeans or chinos, and you’ll love the way it gives a smart sophisticated look.",
    images:["https://uniworthdress.com/uploads/product/a66054fbed592f2aa4cb2b9af3401a62.jpg","https://uniworthdress.com/uploads/product/0ae2db9f9113aebbba2fcce1f93c01e2.jpg","https://uniworthdress.com/uploads/product/3dfb0749f7566476f1a21ffbea1d5f83.jpg","https://uniworthdress.com/uploads/product/TBC2404.jpg"]
  }, 
  {
    id:9,
    name:"Red Printed Band Collar Cotton T-shirt",
    category:"Summer Collection",
    subCategory:"T Shirts",
    brand:"Sale",
    totalPrice:3595,
    discountedPrice:2337,
    productedDetail:[
      {Color:"Red"},
      {Sleeve:"Half Sleeves"},
      {Fit:"Regular Fit"},
      {CuffStyle:"Hem"},
      {CollarStyle:"Band Collar"},
      {Pattern:"Plain"},
      {Style:"Printed"},
      {Fabric:"100% Cotton"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 10 },
    ],
    desc:"This shirt features a sleek and minimalistic collar band, typically measuring two to five centimeters in height, running seamlessly around the neckline without any folding or turndown. It’s perfect for pairing with denim jeans or chinos, and you’ll love the way it gives a smart sophisticated look.",
    images:["https://uniworthdress.com/uploads/product/b33b45451a36fd81a9d93be9407952f8.jpg","https://uniworthdress.com/uploads/product/TBC2409-1.jpg","https://uniworthdress.com/uploads/product/TBC2409-1...jpg","https://uniworthdress.com/uploads/product/TBC2409-1......jpg"]
  }, 
  // Premium Tee
  {
    id:10,
    name:"Sky Plain Premium Tee",
    category:"Summer Collection",
    subCategory:"Premium Tee",
    brand:"Premium Tee",
    totalPrice:2375,
    discountedPrice:2375,
    productedDetail:[
      {Color:"Sky"},
      {CollarStyle:"Crew Neck"},
      {CuffStyle:"Hem"},
      {Fabric:"Cotton Spandex"},
      {Pattern:"Plain"},
      {Sleeve:"Half Sleeves"},
      {Fit:"Regular Fit"},
      {Style:"Basic"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"Basic premium-fit plain T-shirt for a casual and smart look. The premium and breathable quality of the fabric ensure ultimate comfort and diversity to carry the product from day to evening wear. It’s available in color choice of your need.",
    images:["https://uniworthdress.com/uploads/product/TPT2410-1..jpg?h=120","https://uniworthdress.com/uploads/product/TPT2410-1...jpg?h=120","https://uniworthdress.com/uploads/product/TPT2410-1....jpg?h=120"]
  }, 
  {
    id:11,
    name:"White Plain Premium Tee",
    category:"Summer Collection",
    subCategory:"Premium Tee",
    brand:"Basic Tees",
    totalPrice:2375,
    discountedPrice:2375,
    productedDetail:[
      {CollarStyle:"Crew Neck"},
      {CuffStyle:"Hem"},
      {Fabric:"Cotton Spandex"},
      {Pattern:"Plain"},
      {Sleeve:"Half Sleeves"},
      {Style:"Basic"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"Basic premium-fit plain T-shirt for a casual and smart look. The premium and breathable quality of the fabric ensure ultimate comfort and diversity to carry the product from day to evening wear. ",
    images:["https://uniworthdress.com/uploads/product/ad5ebacdd30bbce3089fe365a6f324fa.jpg","https://uniworthdress.com/uploads/product/fdf7eefa7bc3532ad6cf5dbbf2c01ebb.jpg","https://uniworthdress.com/uploads/product/TPT2400-1.jpg","https://uniworthdress.com/uploads/product/TPT2400-1...jpg"]
  }, 
  {
    id:12,
    name:"British Green Plain Premium Tee",
    category:"Summer Collection",
    subCategory:"Premium Tee",
    brand:"Premium Tee",
    totalPrice:3395,
    discountedPrice:2375,
    productedDetail:[
      {CollarStyle:"Crew Neck"},
      {CuffStyle:"Hem"},
      {Fabric:"Cotton Spandex"},
      {Pattern:"Plain"},
      {Sleeve:"Half Sleeves"},
      {Style:"Basic"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"Basic premium-fit plain T-shirt for a casual and smart look. The premium and breathable quality of the fabric ensure ultimate comfort and diversity to carry the product from day to evening wear. ",
    images:["https://uniworthdress.com/uploads/product/2593a7c873605683b66c7a571c69ce8e.jpg","https://uniworthdress.com/uploads/product/8668c2835c3cbfac00c41dc4f4301408.jpg","https://uniworthdress.com/uploads/product/db99689aa536530ea7913651eee073e8.jpg","https://uniworthdress.com/uploads/product/TPT2405-1.jpg"]
  }, 
  // Polo
  {
    id:13,
    name:"Black Color Block Unity Polo Shirt",
    category:"Summer Collection",
    subCategory:"Polo",
    brand:"Polo",
    totalPrice:3795,
    discountedPrice:3036,
    productedDetail:[
      {Color:"Black"},
      {Sleeve:"Half Sleeves"},
      {Fit:"Regular  Fit"},
      {CuffStyle:"Rib"},
      {CollarStyle:"Polo"},
      {Pattern:"Plain"},
      {Style:"Cut n Sew"},
      {Fabric:"100% Cotton"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"Experience unmatched comfort and style with this high-quality cotton polo shirt, designed in a striking green and black color theme. This polo shirt is a bold statement of patriotism. The word PAKISTAN is prominently embroidered across the chest, accompanied by the national motto Unity, Faith, Discipline, making it a powerful symbol of national pride and unity. Whether you're at a casual outing or a national celebration, this polo allows you to proudly display your love for your country.",
    images:["https://uniworthdress.com/uploads/product/b80a2411383315e781cc974931ab1eaf.jpg","https://uniworthdress.com/uploads/product/1f8ec003036934bdbe61204f9cf0e860.jpg","https://uniworthdress.com/uploads/product/fd0258a3bb2267c0163f03fab95e31b6.jpg","https://uniworthdress.com/uploads/product/TP2439.jpg"]
  },
  {
    id:14,
    name:"Athletics Red Pique Polo Shirt",
    category:"Summer Collection",
    subCategory:"Polo",
    brand:"Sale",
    totalPrice:4295,
    discountedPrice:2792,
    productedDetail:[
      {CollarStyle:"Polo"},
      {Color:"Red"},
      {CuffStyle:"Rib"},
      {Fabric:"100% Cotton"},
      {Fit:"Regular  Fit"},
      {Pattern:"Plain"},
      {Sleeve:"Half Sleeves"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 0 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"Our polo shirt is the go-to choice for all seasons and an absolute wardrobe essential. Its pique fabric gives it a naturally mechanical stretch for a soft wrinkle-free look, also making it durable and comfortable to wear for long hours. It is suitable to style with a variety of combinations and layers.",
    images:["https://uniworthdress.com/uploads/product/4adc9a8c9337a283cc3a73b238a91382.jpg","https://uniworthdress.com/uploads/product/1759cca6dd2724007c778f7ca1397049.jpg","https://uniworthdress.com/uploads/product/8fc2ca978358e483559310c26bdd5ee8.jpg","https://uniworthdress.com/uploads/product/TP2458.jpg"]
  },
  {
    id:15,
    name:"Apricot Plain Pique Polo Shirt",
    category:"Summer Collection",
    subCategory:"Polo",
    brand:"Sale",
    totalPrice:3495,
    discountedPrice:2796,
    productedDetail:[
      {Color:"Apricot"},
      {Sleeve:"Half Sleeves"},
      {Fit:"Regular  Fit"},
      {CuffStyle:"Rib"},
      {CollarStyle:"Polo"},
      {Pattern:"Plain"},
      {Style:"Basic"},
      {Fabric:"100% Cotton"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 0 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 10 },
    ],
    desc:"Our polo shirt is the go-to choice for all seasons and an absolute wardrobe essential. Its pique fabric gives it a naturally mechanical stretch for a soft wrinkle-free look, also making it durable and comfortable to wear for long hours. It is suitable to style with a variety of combinations and layers.",
    images:["https://uniworthdress.com/uploads/product/5458c675d9f35cbfeae63ffb6f46c034.jpg","https://uniworthdress.com/uploads/product/d2cba97e234903defd650e209f39d942.jpg","https://uniworthdress.com/uploads/product/2db42c8d17f290fc4efdeb1da4381ab0.jpg","https://uniworthdress.com/uploads/product/TP2416.jpg"]
  },
  // Graphic Shirts 
  {
    id: 16,
    name: "Legendaddy Navy Crew Neck T-shirt",
    category: "Summer Collection",
    subCategory: "Graphic Tees",
    brand: "Graphic Tees",
    totalPrice: 2295,
    discountedPrice: 1136,
    productedDetail: [
      { Color: "Turquoise" },
      { Sleeve: "Half Sleeves" },
      { Fit: "Smart Fit" },
      { CuffStyle: "Hem" },
      { CollarStyle: "Crew Neck" },
      { Pattern: "Plain" },
      { Style: "Embriodery" },
      { Fabric: "100% Cotton" },
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],

    desc: "Add contemporary style to your casual wear assortment with this elegant crew neck T-shirt. This T-shirt is made using the latest dying techniques and is machine stitched that gives the shirt superior resistance against color fading, pilling, staining and wrinkles. This gives a longer life to your T-shirt.",
    images: [
      "https://uniworthdress.com/uploads/product/18e7bf3949c32d673b8788f262da5e2c.jpg",
      "https://uniworthdress.com/uploads/product/8907845d31e559c4ab56378f8dd4c975.jpg",
      "https://uniworthdress.com/uploads/product/TCN2423.jpg",
      "https://uniworthdress.com/uploads/product/TCN2423...jpg",
    ],
  },
  {
    id: 1,
    name: "Legendaddy Navy Crew Neck T-shirt",
    category: "Summer Collection",
    subCategory: "Graphic Tees",
    brand: "Graphic Tees",
    totalPrice: 2295,
    discountedPrice: 1836,
    productedDetail: [
      { Color: "Navy" },
      { Sleeve: "Half Sleeves" },
      { Fit: "Crew Fit" },
      { CuffStyle: "Hem" },
      { CollarStyle: "Crew Neck" },
      { Pattern: "Plain" },
      { Style: "Printed" },
      { Fabric: "100% Cotton" },
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],

    desc: "This crew neck shirt is a casual everyday wear and a super comfortable choice. Made from high-quality fabric, this shirt is extremely lightweight and has a natural stretch. You can get this shirt to elevate your wardrobe with comfort, style, and versatility.",
    images: [
      "https://uniworthdress.com/uploads/product/TCN2440.jpg",
      "https://uniworthdress.com/uploads/product/TCN2440...jpg",
      "https://uniworthdress.com/uploads/product/TCN2440....jpg",
    ],
  },

  // Basic Tees 
  {
    id:17,
    name:"Black Plain Basic Tee",
    category:"Summer Collection",
    subCategory:"Basic Tees",
    brand:"Basic Tees",
    totalPrice:2375,
    discountedPrice:2375,
    productedDetail:[
      {CollarStyle:"Crew Neck"},
      {CuffStyle:"Hem"},
      {Fabric:"Cotton Spandex"},
      {Pattern:"Plain"},
      {Sleeve:"Half Sleeves"},
      {Style:"Basic"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 0 },
    ],
    desc:"Basic premium-fit plain T-shirt for a casual and smart look. The premium and breathable quality of the fabric ensure ultimate comfort and diversity to carry the product from day to evening wear. ",
    images:["https://uniworthdress.com/uploads/product/dcbf786afc3d49cf0e4b9a724a393c8e.jpg","https://uniworthdress.com/uploads/product/09bd2560a9acd89be232aee8402eec06.jpg","https://uniworthdress.com/uploads/product/26b4d63ef6a0ea2016556368f70a08b4.jpg","https://uniworthdress.com/uploads/product/TEE2400-1..jpg"]
  }, 
  {
    id: 2,
    name: "Green Plain Smart Fit Casual Shirt",
    category: "Summer Collection",
    subCategory: "Sale",
    brand: "Sale",
    totalPrice: 3995,
    discountedPrice: 1996,
    productedDetail: [
      { Color: "Green" },
      { Sleeve: "Full Sleeves" },
      { Fit: "Smart Fit" },
      { CuffStyle: "Round Cuff" },
      { CollarStyle: "Button Down Collar" },
      { Pattern: "Plain" },
      { Style: "Designer Shirt" },
      { Fabric: "100% Cotton" },
    ],
    size_stock: [
      { size: "XS", stock: 0 },
      { size: "S", stock: 10 },
      { size: "M", stock: 0 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 0 },
      { size: "XXL", stock: 0 },
    ],

    desc: "Soft and stylish this full sleeve casual shirt will keep you comfortable yet graceful. The classical shade and design combination enable you to wear this shirt with a variety of trousers and walk into any semi-formal or casual event.",
    images: [
      "https://uniworthdress.com/uploads/product/CS2192..jpg",
      "https://uniworthdress.com/uploads/product/CS2192...jpg",
      "https://uniworthdress.com/uploads/product/CS2192......jpg",
      "https://uniworthdress.com/uploads/product/CS2192.....jpg",
    ],
  },
  // Formal Shirts
  {
    id: 3,
    name: "White Self Tailored Smart Fit Shirt",
    category: "Shirts",
    subCategory: "Formal Shirts",
    totalPrice: 9975,
    discountedPrice: 7980,
    productedDetail: [
      { Sleeve: "Full Sleeves" },
      { CuffStyle: "Round Cuff" },
      { CollarStyle: "Extrawide Collar" },
      { Pattern: "Self" },
      { Style: "Formal Shirt" },
      { Fabric: "100% Cotton" },
    ],
    size_stock: [
      { size: "14½", stock: 10 },
      { size: "15", stock: 10 },
      { size: "15½", stock: 10 },
      { size: "16", stock: 10 },
      { size: "16½", stock: 10 },
      { size: "17", stock: 10 },
      { size: "17½", stock: 10 },
      { size: "18", stock: 0 },
      { size: "18½", stock: 0 },
    ],
    desc: "Uniworth features Self Print Shirts with elegant self-prints on the same color base. The fabric is a soft, midweight cotton-blend Polyester. An abstract, impressionist print, and expert eye-to-detail stitching invigorate this Self-Print Shirt. To showcase the pattern in the same color base and designer details, this shirt is best worn with a contrasting color tie and jacket.",
    images: [
      "https://uniworthdress.com/uploads/product/FS20363SF.jpg",
      "https://uniworthdress.com/uploads/product/FS20363SF...jpg",
      "https://uniworthdress.com/uploads/product/FS20363SF.....jpg",
      "https://uniworthdress.com/uploads/product/FS20363SF....jpg",
    ],
  },
  // Stripe Shirts
  {
    id: 4,
    name: "Red Stripe Tailored Smart Fit Shirt",
    category: "Shirts",
    subCategory: "Stripe Shirts",
    totalPrice: 5995,
    discountedPrice: 4796,
    productedDetail: [
      { CollarStyle: "French Collar" },
      { CuffStyle: "Round Cuff" },
      { Fabric: "80% Cotton 20% Polyester" },
      { Pattern: "Stripe" },
      { Sleeve: "Full Sleeves" },
      { Style: "Formal Shirt" },
    ],
    size_stock: [
      { size: "14½", stock: 10 },
      { size: "15", stock: 10 },
      { size: "15½", stock: 10 },
      { size: "16", stock: 10 },
      { size: "16½", stock: 10 },
      { size: "17", stock: 10 },
      { size: "17½", stock: 10 },
      { size: "18", stock: 0 },
      { size: "18½", stock: 0 },
    ],
    desc: "A classic, our Stripe shirt is woven in luxurious cotton for a soft and sumptuous feel. Added stretch offers comfort all day long. Non-iron with taped seams, classic collar, and with crease-resistant technology for a sharp appearance. It gives you a flattering, impeccable look whether you’re off to a business meeting or a formal event. A meeting staple. Cut from superfine cotton for the desired silhouette. Ram-skull on the chest - its usual place.",
    images: [
      "https://uniworthdress.com/uploads/product/FS2724-2SF.jpg",
      "https://uniworthdress.com/uploads/product/FS2724-2SF...jpg",
      "https://uniworthdress.com/uploads/product/FS2724-2SF......jpg",
      "https://uniworthdress.com/uploads/product/FS2724-2SF....jpg",
    ],
  },
  // Plain Shirts
  {
    id:5,
    name:"Black Plain Classic Fit Shirt",
    category:"Shirts",
    subCategory:"Plain Shirts",
    totalPrice:6995,
    discountedPrice:5596,
    productedDetail:[
      {CollarStyle:"French Collar"},
      {CuffStyle:"Round Cuff"},
      {Fabric:"80% Cotton 20% Polyester"},
      {Pattern:"Plain"},
      {Sleeve:"Full Sleeves"},
      {Style:"Formal Shirt"},
    ],
    size_stock: [
      { size: "14½", stock: 0 },
      { size: "15", stock: 0 },
      { size: "15½", stock: 10 },
      { size: "16", stock: 10 },
      { size: "16½", stock: 10 },
      { size: "17", stock: 10 },
      { size: "17½", stock: 10 },
      { size: "18", stock: 10 },
      { size: "18½", stock: 10 },
    ],
    desc:"Uniworth’s plain shirt is the ultimate choice for stylish men who don’t want a full stop to their trend-following. A relaxed-fit collared shirt featuring long sleeves with buttoned cuffs. Our Regular fit is the roomiest choice in shirts, and offers maximum comfort, generously cutting across the waist, creating a seamless straight silhouette. It doesn't get more classic. Crafted from a stretch cotton fabric. In a Regular fit.",
    images:["https://uniworthdress.com/uploads/product/FS1307-5RF.jpg?h=120","https://uniworthdress.com/uploads/product/FS1307-5RF...jpg?h=120","https://uniworthdress.com/uploads/product/FS1307-5RF.....jpg?h=120","https://uniworthdress.com/uploads/product/FS1307-5RF....jpg?h=120"]
  },
  // Undergarments
  {
    id:6,
    name:"Vest",
    category:"Accessories",
    subCategory:"Undergarments",
    totalPrice:1095,
    discountedPrice:876,
    productedDetail:[
      {CollarStyle:"U- Neck"},
      {Fabric:"100% Cotton"},
      {Pattern:"Plain"},
      {Sleeve:"Half Sleeves"},
      {Style:"Seamless Vest"},
    ],
    size_stock: [
      { size: "S", stock: 100 },
      { size: "M", stock: 20 },
      { size: "L", stock: 100 },
      { size: "XL", stock: 30 },
      { size: "XXL", stock: 10 },
    ],
    desc:"This amazing short sleeve vest is made with an ultra-fitting for active performance. Whether you are cycling trekking or working in your office our sporty undergarment will keep you cool fresh and comfortable. Order now to have this essential men wear in your wardrobe.",
    images:["https://uniworthdress.com/uploads/product/UGV2300H.jpg","https://uniworthdress.com/uploads/product/UGV2300H...jpg","https://uniworthdress.com/uploads/product/UGV2300H....jpg"]
  },

  // {
  //   id:3,
  //   name:"",
  //   category:"",
  //   subCategory:"",
  //   totalPrice:123,
  //   discountedPrice:123,
  //   productedDetail:[
  //     {Color:""},
  //     {Sleeve:""},
  //     {Fit:""},
  //     {CuffStyle:""},
  //     {CollarStyle:""},
  //     {Pattern:""},
  //     {Style:""},
  //     {Fabric:""},
  //   ],
  //   desc:"",
  //   images:["","","",""]
  // },
  // {
  //   id:3,
  //   name:"",
  //   category:"",
  //   subCategory:"",
  //   totalPrice:123,
  //   discountedPrice:123,
  //   productedDetail:[
  //     {Color:""},
  //     {Sleeve:""},
  //     {Fit:""},
  //     {CuffStyle:""},
  //     {CollarStyle:""},
  //     {Pattern:""},
  //     {Style:""},
  //     {Fabric:""},
  //   ],
  //   desc:"",
  //   images:["","","",""]
  // },
];
